// Generated by EmDash CLI
// Do not edit manually - run `emdash types` to regenerate

/// <reference types="emdash/locals" />

import type { ContentBylineCredit, PortableTextBlock, TaxonomyTerm } from "emdash";

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  content?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Piece {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  featured_image: { id: string; src?: string; alt?: string; width?: number; height?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };
  summary?: string;
  featured?: boolean;
  materials?: string;
  color?: string;
  dimensions?: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    pieces: Piece;
  }
}
